app/models.py
import datetime
from . import db


class User(db.Model):
    id = db.Column(db.INTEGER, primary_key=True, autoincrement=True)
    registered_on = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow())
    fname = db.Column(db.String(20), nullable=False)
    lname = db.Column(db.String(20)) 
    email = db.Column(db.String(32))
    phone = db.Column(db.String(15), unique=True, nullable=False)
    orders = db.relationship('Orders', backref='user', lazy=True)


class Orders(db.Model):
    id = db.Column(db.INTEGER, primary_key=True)
    ordered_on = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow())
    order_data = db.Column(db.PickleType, nullable=True)
    ordered_by = db.Column(db.INTEGER, db.ForeignKey('user.id'), nullable=False)


class Categories(db.Model):
    id = db.Column(db.INTEGER, primary_key=True, autoincrement=True)
    category_name = db.Column(db.String(20), nullable=False)
    orders = db.relationship('FoodItems', backref='categories', lazy=True)


class FoodItems(db.Model):
    id = db.Column(db.INTEGER, primary_key=True)
    added_on = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow())
    food_name = db.Column(db.String(20), nullable=False)
    food_description = db.Column(db.Text, nullable=False)
    food_img = db.Column(db.Text, nullable=False)
    food_price = db.Column(db.INTEGER, nullable=False)
    is_available = db.Column(db.Boolean, default=True)
    food_category = db.Column(db.INTEGER, db.ForeignKey('categories.id'), nullable=False)


# food review table
# admin table

# orders data table
'''
date -> primary_key
food_id -> foriegn key
ordered frequency
'''

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_socketio import SocketIO, emit, join_room


db = SQLAlchemy()
socketio = SocketIO()

def create_app():
    app = Flask(__name__)
    app.config.from_pyfile("config.py")


    from .user import routes as user_routes
    from .admin import routes as admin_routes
    from .cook import routes as cook_routes


    db.init_app(app)
    socketio.init_app(app, cors_allowed_origins="*")

    app.register_blueprint(user_routes.user)
    app.register_blueprint(admin_routes.adminbp)
    app.register_blueprint(cook_routes.cookbp)


    with app.app_context():
        db.create_all()
    return app

app/admin/routes.py
from flask import Blueprint, render_template


adminbp = Blueprint('adminbp', __name__)


@adminbp.route('/admin')
def admin():
    return render_template('admin.html')

app/cook/routes.py
from flask import Blueprint, render_template


cookbp = Blueprint('cookbp', __name__)


@cookbp.route('/cook_ui')
def cook_ui():
    return render_template('cook_ui.html')


@cookbp.route('/cook_login')
def cook_login():
    return render_template('cook_login.html')


@cookbp.route('/view_order/<order_id>')
def view_order(order_id):
    return render_template('cook_view_order.html', order_id=order_id)

app/user/routes.py
from flask import Blueprint, render_template, request, jsonify, session
from .. import socketio, db, emit, join_room
from ..models import *
import json


user = Blueprint('user',__name__)


@user.app_template_filter('to_string')
def to_string(value):
    return json.dumps(value)


@user.route('/set_table/<table_id>')
def set_table(table_id):
    return render_template('create_table.html')


@user.route('/create_table', methods=['POST'])
def create_table():
    data = request.get_json(force=True)
    user = User.query.filter_by(phone=data['phone']).first()
    session['user'] = data['phone']
    if not user:
        new_user = User(fname=data['fname'],lname=data['lname'],email=data['email'],phone=data['phone'])
        db.session.add(new_user)
        db.session.commit()
    return jsonify(resp='ok')


@user.route('/')
def index():
    categories = Categories.query.all()
    # query only new and popular foods 4 in each row
    return render_template('index.html', categories=categories)


@user.route('/cart')
def cart():
    categories = Categories.query.all()
    return render_template('cart.html', categories=categories)


@user.route('/history')
def history():
    categories = Categories.query.all()
    orders = Orders.query.order_by(Orders.ordered_on.desc()).filter_by(ordered_by=session['user']).all()
    return render_template('account_history.html', categories=categories, orders=orders)


@user.route('/order_details/<order_id>')
def order_details(order_id):
    order = Orders.query.filter_by(id=order_id).first()
    return render_template('order_details.html', order=order)


@user.route('/orders')
def orders():
    # view current session orders
    return render_template('orders.html')


@user.route('/error')
def error():
    # render this when user hasnt scanned the qr instead used direct url for other routes without setting table
    return render_template('error.html')


@socketio.on('join')
def on_join(data):
    join_room(data['table_id'])


@socketio.on('update')
def new_order(data):
    # commit to db after  the cook sets the status as completed. till then store in localstorage
    order_id = data['order_id']
    ordered_by = data['identifier']
    new_order = Orders(id=order_id, order_data=data, ordered_by=ordered_by)
    db.session.add(new_order)
    db.session.commit()
    print('order received')
    emit('ord_updates', data, broadcast=True)


@socketio.on('order received')
def order_received(data):
    emit('order update', "Order has been received", to=data['table_id'])


@socketio.on('foodstatus')
def food_status(data):
    print(data)
    emit('foodupdate', data, to=data['table_id'])

app/templates/account_history.html
{% extends "layout.html" %}
{% block content %}
<div class="page-content">
	<div class="holder breadcrumbs-wrap mt-0">
	<div class="container">
		<ul class="breadcrumbs">
			<li><a href="index.html">Home</a></li>
			<li><span>Past Orders</span></li>
		</ul>
	</div>
</div>
	<div class="holder">
	<div class="container">
		<div class="row">
			<div class="col-md-14 aside">
			<h1 class="mb-3">Order History</h1>
				<div class="table-responsive">
					<table class="table table-bordered table-striped table-order-history">
						<thead>
						<tr>
							<th scope="col"># </th>
							<th scope="col">Order Number</th>
							<th scope="col">Ordered On</th>
							<th scope="col">Status</th>
							<th scope="col">Total Price</th>
							<th scope="col"></th>
						</tr>
						</thead>
						<tbody>
							{% for order in orders %}
								<tr>
									<td>{{ loop.index }}</td>
									<td><b>{{ order.id }}</b> <a href="{{ url_for('user.order_details', order_id=order.id) }}" class="ml-1">View Details</a></td>
									<td>{{ order.ordered_on.strftime("%d.%m.%Y") }}</td>
									<td>{{ order.order_data['order_status'] }}</td>
									<td><span class="color">₹ {{ order.order_data['total'] }}</span></td>
									<td><a href="#" class="btn btn--grey btn--sm">REORDER</a></td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
			</div>
		</div>
	</div>
</div>
</div>

</html>
{% endblock content %}

app/templates/cart.html
{% extends "layout.html" %}
{% block content %}

<div class="page-content">
	<div class="holder breadcrumbs-wrap mt-0">
	<div class="container">
		<ul class="breadcrumbs">
			<li><a href="index.html">Home</a></li>
			<li><span>Cart</span></li>
		</ul>
	</div>
</div>
	<div class="holder">
        <div class="food-items container">
                <h1 class="text-center">Food Basket</h1>
                <div class="cart-table">
            <div class="cart-table-prd cart-table-prd--head py-1 d-none d-md-flex">
                <div class="cart-table-prd-image text-center">
                    Image
                </div>
                <div class="cart-table-prd-content-wrap">
                    <div class="cart-table-prd-info">Name</div>
                    <div class="cart-table-prd-qty">Qty</div>
                    <div class="cart-table-prd-price">Price</div>
                    <div class="cart-table-prd-action">&nbsp;</div>
                </div>
            </div>
        </div>
    </div>
		<div class="text-center mt-1"><button class="btn btn--grey order-btn">order Now</button></div>
{% endblock content %}

{% block scripts %}

<script>
    var food_items = JSON.parse(window.localStorage.getItem('cart'));

    var old_orders = JSON.parse(window.localStorage.getItem('ordered'));

    function getObject(food_id){
        let obj = food_items.cart_items.find(o => o.food_id === food_id);
        return obj
    }

    function updateObject(food_id, qty){
        food_items.cart_items.find((obj, pos) => {
            if (obj.food_id === food_id){
                food_items.cart_items[pos].data.quantity = qty;
                window.localStorage.setItem('cart', JSON.stringify(food_items));
                return true;
            }
        })
    }

    function deleteObject(food_id){
        food_items = food_items.cart_items.filter(obj => obj.food_id != food_id);
        window.localStorage.setItem('cart', JSON.stringify({"cart_items":food_items}));
        return true;
    }

    $(document).ready(function(){
        var total = 0;
        var item_counts = 0;

        if (JSON.parse(window.localStorage.getItem('cart')).cart_items.length < 1){
            var html_tag = `
            <div class="holder mt-0">
                <div class="container">
                    <div class="page404-bg">
                        <div class="page404-text">
                            <div class="txt2">Your shopping cart is empty!</div>
                            <div class="add-food" style="margin-top: 3%">
                                Don't worry, you can add 🍚 🥗 from <a href="{{ url_for('user.index') }}" style="color:#17c6aa;text-decoration:underline;">here</a>.
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            `
            $(".holder").remove();
            $(".page-content").remove();
            $("body").append(html_tag);
        } 
        else{
            for (i=0; i<food_items.cart_items.length; i++){
                var cur_item = food_items.cart_items[i];
                var html_tag = `
                <div class="cart-table-prd">
                    <div class="cart-table-prd-image">
                        <a href="#" class="prd-img"><img class="lazyload fade-up" src="" data-src="${cur_item.data.food_img}" alt=""></a>
                    </div>
                    <div class="cart-table-prd-content-wrap">
                        <div class="cart-table-prd-info">
                            <div class="cart-table-prd-price">
                                <div class="price-new">₹ ${cur_item.data.price}</div>
                            </div>
                            <h2 class="cart-table-prd-name"><a href="#">${cur_item.data.food_name}</a></h2>
                        </div>
                        <div class="cart-table-prd-qty">
                            <div class="qty qty-changer">
                                <button class="decrease"></button>
                                <input type="text" class="qty-input" value="${cur_item.data.quantity}" id="${cur_item.food_id}" data-min="0" data-max="1000">
                                <button class="increase"></button>
                            </div>
                        </div>
                        <div class="cart-table-prd-price-total total-price">
                            ₹ ${cur_item.data.price*cur_item.data.quantity}
                        </div>
                    </div>
                    <div class="cart-table-prd-action">
                        <a href="#" class="cart-table-prd-remove" data-tooltip="Remove Product"><i class="icon-recycle"></i></a>
                    </div>
                </div>`
                $(".food-items").append(html_tag);
                total = total+(cur_item.data.price*cur_item.data.quantity);
                item_counts = item_counts+parseInt(cur_item.data.quantity);
            }
        }

        $(".increase, .decrease").on('click', function(){
            var $idu = $(this);
            var qty = $idu.closest('div').find('.qty-input')[0];
            var per_item_price = $idu.parentsUntil('div.cart-table-prd').find('.price-new')[0].innerText;
            var food_id = qty.id;
            // update total price too

            if ($idu.is('.increase')){
                qty.value = parseInt(qty.value)+1;
                total = total+parseInt(per_item_price.split(' ')[1]);
                item_counts = item_counts+1;
            } else{
                if (parseInt(qty.value) > 0){
                    qty.value = parseInt(qty.value)-1;
                    total = total-parseInt(per_item_price.split(' ')[1]);
                    item_counts = item_counts-1;
                }
            }
            // update total price or item
            $idu.parentsUntil('div.cart-table-prd').find('.total-price')[0].innerText = '₹ ' + qty.value*parseInt(per_item_price.split(' ')[1]);
            
            updateObject(food_id, qty.value);
        })

        $(".cart-table-prd-remove").on('click', function(){
            var obj = $(this).parent().parent().find('.qty-input')[0];
            var food_id = obj.id;
            var per_item_price = $(this).parent().parent().find('.price-new')[0].innerText;
            deleteObject(food_id);
            $(this).parent().parent()[0].remove();
            total=total-(parseInt(per_item_price.split(' ')[1])*parseInt(obj.value));
            item_counts = item_counts-parseInt(obj.value);
        })

        $(".order-btn").on('click', function(){
            Swal.fire({
                title: 'Order Now?',
                text: `Ordering ${item_counts} items worth ₹ ${total}.`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Lets, do it.'
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire(
                    'Order Placed',
                    'Your order has been placed. We will let you know when chef starts preparing your order.',
                    'success'
                    );
                    food_items.ordered_on = new Date().toLocaleDateString('in').replaceAll('/','.');
                    food_items.order_status = 'ordered';
                    food_items.total = total;
                    old_orders.data.push(food_items);
                    window.localStorage.setItem('ordered', JSON.stringify(old_orders));
                    window.localStorage.setItem('cart', JSON.stringify({"cart_items":[], "table_id":null, "order_id":null, "ordered_on": null, "order_status":null, "total":null}));
                    socket.emit('update', food_items);
                    
                }
            })
        })
    })

    socket.on('foodupdate', function(data){
			console.log('yeah');
			Swal.fire({
					title:"order "+data.status,
					text: data.message,
					icon:data.icon,
				})
			$(".order_status_"+data.order_id).text(data.status=='accepted' ? 'Preparing': 'Canceled');
		})

    // when cook accepts order update the user.
    socket.on('order update', function(msg){
        const audio_path = '{{ url_for("static", filename="sounds/order_received.wav") }}';
        Swal.fire({
            title: 'Order accepted',
            text: 'Your order #123 is being prepared. Please wait',
            icon: 'success',
            didOpen: function () {
                const audio = new Audio(audio_path);
                audio.autoplay = true;
                audio.play();
            }
        })
    })

</script>
</html>
{% endblock scripts %}

app/templates/cook_login.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cook Login</title>
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='js/sockets.js') }}"></script>
</head>
<body>
    <input type="text" name="username" id="username" placeholder="username">
    <button id="login-btn">Login</button>
</body>

<script>
    window.localStorage.setItem('cook_data', JSON.stringify({'data': {'completed':[], 'preparing':[], 'inqueue':[]}}))
    window.localStorage.setItem('cook', 'anirudhmp')

    $("#login-btn").on('click', function(){
        window.location.href = '{{ url_for("cookbp.cook_ui") }}'
    })
</script>
</html>

app/templates/create_table.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>Table registration</title>
	<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}" />

	<link href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='fonts/icomoon/icons.css') }}" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Open%20Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
</head>
<body class="has-smround-btns has-loader-bg equal-height has-sm-container">

<header class="hdr-wrap">

	<div class="holder">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-18 col-lg-12">
					<h2 class="text-center">Before You Order...</h2>
					<div class="form-wrapper">
						<p>To access your past orders, and to take advantage of our loyalty programme, fill the form below.</p>
						
							<div class="row">
								<div class="col-sm-9">
									<div class="form-group">
										<input type="text" class="form-control" placeholder="First name" id="fname" required>
									</div>
								</div>
								<div class="col-sm-9">
									<div class="form-group">
										<input type="text" class="form-control" placeholder="Last name" id="lname" required>
									</div>
								</div>
							</div>
							<div class="form-group">
								<input type="text" class="form-control" placeholder="E-mail (Optional)" id="email">
							</div>
							<div class="form-group">
								<input type="text" class="form-control" placeholder="Phone" id="phone" required>
							</div>
							<div class="form-group">
								<input type="text" class="form-control" placeholder="Table id" id="table-id" readonly>
							</div>
							<div class="text-center">
								<button class="btn start-btn">Start Ordering</button>
							</div>
						
					</div>
				</div>
			</div>
		</div>
	</div>
</body>

<script>
    window.localStorage.clear();

    window.localStorage.setItem('cart', JSON.stringify({"cart_items":[], "table_id":null, "order_id":null, "ordered_on": null, "order_status":null, "total":null, "identifier": null}));

	window.localStorage.setItem('ordered', JSON.stringify({"data":[]}));

	Swal.fire("Note: we use your phone number to store your orders data.")

	$("#fname").keyup(function() {
		$("#table-id").val('Table ID is "'+$("#fname").val() +"#"+window.location.pathname.split('/')[2]+'"');
	})

    $(".start-btn").on('click', function(){
        var fname = $("#fname").val();
        var lname = $("#lname").val();
        var email = $("#email").val();
        var phone = $("#phone").val();

        if (fname == null || fname == '' || lname == null || lname == '' || phone == null || phone == ''){
            Swal.fire({
                icon: 'error',
                title: 'Missing Data',
                text: 'please fill the form...',
            })
        } else{
            var table_id = fname+'#'+window.location.pathname.split('/')[2];
            var userdata = {
                fname:fname,
                lname:lname,
                email:email,
                phone:phone,
                table_id:table_id
            };
            window.localStorage.setItem('table_id', table_id);

            $.ajax({
                type: 'POST',
                url: "{{ url_for('user.create_table') }}",
                contentType: 'application/json',
                data: JSON.stringify(userdata),
                dataType: "json",
                success: function(result){
                    Swal.fire({
                        icon: 'success',
                        title: 'Thank you...',
                        showConfirmButton: true,
                    });
                    window.location = "{{ url_for('user.index') }}";
					window.localStorage.setItem('identifier', phone);
                }
            });
        }
    })
</script>
</html>

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
	    <title>Anirudh M P</title>
    {% endif %}
	<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}" />

	<link href="{{ url_for('static', filename='css/vendor/bootstrap.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/vendor/vendor.min.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='fonts/icomoon/icons.css') }}" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Open%20Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script src="{{ url_for('static', filename='js/sockets.js') }}"></script>
</head>

<body class="has-smround-btns has-loader-bg equal-height">
<header class="hdr-wrap">
	<div class="hdr-content hdr-content-sticky">
		<div class="container">
			<div class="row">
				<div class="col-auto show-mobile">
					<!-- Menu Toggle -->
<div class="menu-toggle"> <a href="#" class="mobilemenu-toggle"><i class="icon-menu"></i></a> </div>
<!-- /Menu Toggle -->
				</div>
				<div class="col-auto hdr-logo">
					<a href="index.html" class="logo"><img srcset="images/skins/fashion/logo.png 1x, images/skins/fashion/logo2x.png 2x" alt="Logo"></a>
				</div>
				<!--navigation-->
				<div class="hdr-nav hide-mobile nav-holder-s">
				</div>
				<!--//navigation-->
				<div class="hdr-links-wrap col-auto ml-auto">
					<div class="hdr-inline-link">
						<!-- Header Search -->
<div class="search_container_desktop">
	<div class="dropdn dropdn_search dropdn_fullwidth">
		<a href="#" class="dropdn-link  js-dropdn-link only-icon"><i class="icon-search"></i><span class="dropdn-link-txt">Search</span></a>
		<div class="dropdn-content">
			<div class="container">
				<form method="get" action="#" class="search search-off-popular">
					<input name="search" type="text" class="search-input input-empty" placeholder="What are you looking for?">
					<button type="submit" class="search-button"><i class="icon-search"></i></button>
					<a href="#" class="search-close js-dropdn-close"><i class="icon-close-thin"></i></a>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- /Header Search -->

</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="hdr">
		<div class="hdr-topline hdr-topline--dark js-hdr-top">
			<div class="container">
				<div class="row flex-nowrap">
					<div class="col hdr-topline-left hide-mobile">

							<div class="hdr_container_desktop">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="hdr-content">
			<div class="container">
				<div class="row">
					<div class="col-auto show-mobile">
						<!-- Menu Toggle -->
<div class="menu-toggle"> <a href="#" class="mobilemenu-toggle"><i class="icon-menu"></i></a> </div>
<!-- /Menu Toggle -->
					</div>
					<div class="col-auto hdr-logo">
						<a href="#" class="logo"><img srcset="images/skins/fashion/logo.png 1x, images/skins/fashion/logo2x.png 2x" alt="Logo"></a>
					</div>
					<!--navigation-->
					<div class="hdr-nav hide-mobile nav-holder justify-content-center px-4">
						<!--mmenu-->
<ul class="mmenu mmenu-js">
	<li class="mmenu-item--simple"><a href="{{ url_for('user.index') }}" class="active">Home</a></li>
	<li class="mmenu-item--simple"><a href="#">Menu</a>
		<div class="mmenu-submenu">
			<ul class="submenu-list">
				{% for category in categories %}
					<li><a href="#">{{ category.category_name }}</a></li>
				{% endfor %}
            </ul>
		</div>
	</li>
	<li><a href="{{ url_for('user.cart') }}">Cart</a></li>
	<li class="mmenu-item--mega"><a href="{{ url_for('user.orders') }}">Orders</a></li>
	<li class="mmenu-item--mega"><a href="{{ url_for('user.history') }}">Past Orders</a>
	</li>
</ul>
					</div>
					<div class="hdr-links-wrap col-auto ml-auto">
						<div class="hdr-inline-link">
							<!-- Header Search -->
<div class="search_container_desktop">
	<div class="dropdn dropdn_search dropdn_fullwidth">
		<a href="#" class="dropdn-link  js-dropdn-link only-icon"><i class="icon-search"></i><span class="dropdn-link-txt">Search</span></a>
		<div class="dropdn-content">
			<div class="container">
				<form method="get" action="#" class="search search-off-popular">
					<input name="search" type="text" class="search-input input-empty" placeholder="What are you looking for?">
					<button type="submit" class="search-button"><i class="icon-search"></i></button>
					<a href="#" class="search-close js-dropdn-close"><i class="icon-close-thin"></i></a>
				</form>
			</div>
		</div>
	</div>
</div>

							<div class="hdr_container_mobile show-mobile">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<div class="header-side-panel">
	<!-- Mobile Menu -->
<div class="mobilemenu js-push-mbmenu">
	<div class="mobilemenu-content">
		<div class="mobilemenu-close mobilemenu-toggle">Close</div>
		<div class="mobilemenu-scroll">
			<div class="mobilemenu-search"></div>
			<div class="nav-wrapper show-menu">
				<div class="nav-toggle">
					<span class="nav-back"><i class="icon-angle-left"></i></span>
					<span class="nav-title"></span>
					<a href="#" class="nav-viewall">view all</a>
				</div>
				<ul class="nav nav-level-1">
					<li><a href="#">Home<span class="arrow"><i class="icon-angle-right"></i></span></a></li>
					<li><a href="#">Menu<span class="arrow"><i class="icon-angle-right"></i></span></a>
						<ul class="nav-level-2">
							{% for category in categories %}
								<li><a href="#">{{ category.category_name }}</a></li>
							{% endfor %}
						</ul>
					</li>
					<li><a href="{{ url_for('user.cart') }}">Cart<span class="arrow"><i class="icon-angle-right"></i></span></a></li>
					<li><a href="#">Orders<span class="arrow"><i class="icon-angle-right"></i></span></a></li>
					<li><a href="{{ url_for('user.history') }}">Past Orders<span class="arrow"><i class="icon-angle-right"></i></span></a></li>
				</ul>
			</div>
			<div class="mobilemenu-bottom">
				</div>
			</div>
		</div>
	</div>
</div>
{% block content %}
{% endblock content %}
    <script src="{{ url_for('static', filename='js/vendor-special/lazysizes.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor-special/ls.bgset.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor-special/ls.aspectratio.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor-special/jquery.ez-plus.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor-special/instafeed.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/vendor.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app-html.js') }}"></script>
</body>

<script>
	socket = io.connect('http://localhost:5000');
	socket.emit('join', {table_id:window.localStorage.getItem('table_id')});
</script>
{% block scripts %}
{% endblock scripts %}